{
 "title": "JMeter_Promethius_Grafana",
 "description": "A grafana dashboard to inspect jmeter metrics via prometheus ",
 "time": { "from": "2026-03-23T18:22:53.960Z", "to": "2026-03-23T18:27:07.319Z" },
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "1s,5s,15m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "jvm_threads_current" }
   ]
  },
  {
   "title": "Total Request ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(jmeter_count_total{})" }
   ]
  },
  {
   "title": "Failure Request Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(jmeter_failure_total{})" }
   ]
  },
  {
   "title": "Failure Rate %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(jmeter_failure_total[$__interval]))/sum(rate(jmeter_count_total[$__interval])))"
    }
   ]
  },
  { "title": "Load Test Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(jmeter_success_total[$__rate_interval]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Среднее время ответа",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jmeter_rt_counter_sum / jmeter_rt_counter_count"
    }
   ]
  },
  {
   "title": "95-й перцентиль времени простоя потоков",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jmeter_idle_time{quantile=\"0.95\"}"
    }
   ]
  },
  {
   "title": "Jmeter Aggregate Report",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(label)(jmeter_count_total{})"
    },
    {
     "expr": "avg(jmeter_summary{}) by (label)"
    },
    {
     "expr": "avg(jmeter_summary{quantile=\"0.9\"}) by (label)"
    },
    {
     "expr": "avg(jmeter_summary{quantile=\"0.95\"}) by (label)"
    },
    {
     "expr": "avg(jmeter_summary{quantile=\"0.99\"})"
    },
    {
     "expr": "min(jmeter_summary{}) by (label)"
    },
    {
     "expr": "max(jmeter_summary{}) by (label)"
    },
    {
     "expr": "(sum(rate(jmeter_failure_total[$__interval]))/sum(rate(jmeter_count_total[$__interval]))) * 100",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "sum(rate(jmeter_count_total[$__interval])) by (label)"
    },
    {
     "expr": "avg(jmeter_rsize_sum{}/1024) by (label)"
    },
    {
     "expr": "avg(jmeter_rsize_count{}/1024) by (label)"
    }
   ]
  },
  {
   "title": "Failure Request Details",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jmeter_failure_total) by (label)"
    }
   ]
  },
  {
   "title": "95-й перцентиль задержки (latency)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jmeter_latency_summary{quantile=\"0.95\"}"
    }
   ]
  },
  {
   "title": "Время ответа",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jmeter_rt_counter{quantile=\"0.95\"}",
     "legendFormat": "95 perc"
    },
    {
     "expr": "jmeter_rt_counter{quantile=\"0.99\"}",
     "legendFormat": "99 perc"
    }
   ]
  },
  {
   "title": "Utils",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Процесс – использование CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Количество загруженных классов в JVM",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_classes_loaded", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Количество открытых файловых дескрипторов",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_open_fds{job=\"jmeter\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error by Transactions",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum by (code,label) (jmeter_failure_total)"
      }
     ]
    },
    {
     "title": "Errors Count",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "sum by (code) (jmeter_failure_total)"
      }
     ]
    }
   ]
  },
  {
   "title": "Test farm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC % time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"jmeter\"}[1m])",
       "legendFormat": "{{instance}} - {{gc}} "
      }
     ]
    },
    {
     "title": "JVM heap  - free memory by pool",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(jvm_memory_pool_bytes_committed {job=~\"jmeter\"}) - (jvm_memory_pool_bytes_used{job=~\"jmeter\"}) ",
       "legendFormat": "{{instance}} - {{pool}}"
      }
     ]
    },
    {
     "title": "JVM heap -  used memory by pool",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(jvm_memory_pool_bytes_used{job=\"jmeter\"}) ",
       "legendFormat": "{{instance}} - {{pool}}"
      }
     ]
    },
    {
     "title": "JVM free memory",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(jvm_memory_bytes_max {job=\"jmeter\"}) - (jvm_memory_bytes_used{job=\"jmeter\"})",
       "legendFormat": "{{instance}} - {{area}}"
      }
     ]
    }
   ]
  }
 ]
}